image:
  repository: oryd/kratos
  tag: v0.11.1
kratos:
  automigration:
    enabled: true
    type: initContainer
  config:
    dsn: postgres://ory:7MKCmw7KkAyQwIiJALcDKp7Vinbnplo8inChpiokTy7ADz95PrPDdvqVMhDAIu48@postgres-ory:5432/kratos
    secrets:
      default:
        - G5zpGur55TehKFPLEKuYW7dCHwiwzTWGBq6yu9m5AHcmdJmP4tfMNS2eLYefAZtCfQYr3W8pHY7rY48NuQF4exBgGV9S8aSthb3xvGcpVZNSfcN9N2feVxBkrzKWLM9J
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: smtp://mailslurper:2500
    selfservice:
      default_browser_return_url: http://127.0.0.1:3000/
    serve:
      public:
        base_url: http://localhost:4433
        cors:
          enabled: true
          allowed_origins:
            - http://localhost:3000        
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
            - Content-Type
          exposed_headers:
            - Content-Type
            - Set-Cookie
      admin:
        base_url: http://localhost:4434
  identitySchemas:
    "identity.default.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "recovery": {
                    "via": "email"
                  },
                  "verification": {
                    "via": "email"
                  }
                }
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        }
      }