apiVersion: v1
kind: Service
metadata:
  name: mailslurper
  namespace: ory-playground
spec:
  selector:
    app: mailslurper
  ports:
  - port: 2500
    targetPort: smtp
    name: smtp
  - port: 8080
    targetPort: www
    name: www
  - port: 8085
    targetPort: service
    name: service
